@hostname = localhost
@port = 3001
@personId = 658d5424cddc722b9b55ea9e
@missingPersonId = 5
@host = http://{{hostname}}:{{port}}

###

DELETE {{host}}/phonebook/{{personId}} HTTP/1.1
Accept: application/json

###

DELETE {{host}}/phonebook/{{missingPersonId}} HTTP/1.1
Accept: application/json