### Get all scores
GET http://localhost:3001/scores

### Create a score
POST http://localhost:3001/scores
Content-Type: application/json

{
  "username": "test",
  "score": 10,
  "date": "2020-01-01T00:00:00.000Z",
  "joke": "6461f476d9a9da9dbeade34e"
}